# Generated by Django 5.2.14 on 2026-07-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocial',
            name='medicos_disponibles',
            field=models.ManyToManyField(blank=True, related_name='obras_sociales', to='app.medico'),
        ),
    ]
