# Generated by Django 5.2.15 on 2026-06-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_especialidad_alter_medico_especialidad_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.TextField(blank=True),
        ),
    ]
